# Generated by Django 5.2.1 on 2025-06-12 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ach_title', models.CharField(max_length=100)),
                ('ach_content', models.TextField()),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='score',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='Tot_Exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='Tot_Hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='password',
            field=models.CharField(default=123456789, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diary_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diarytitle')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ach_time', models.DateTimeField()),
                ('ach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weather_icon', models.CharField(max_length=50)),
                ('color_mix', models.CharField(max_length=50)),
                ('emotion_tag', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PositiveEmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('emotion_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source_event', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_exp_time', models.DateTimeField()),
                ('get_exp', models.IntegerField()),
                ('reason', models.TextField()),
                ('current_total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('special_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialdate')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
