# Generated by Django 5.2.1 on 2025-07-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo_owner_alter_photo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='emotion',
            field=models.CharField(choices=[('快樂', '快樂'), ('憤怒', '憤怒'), ('悲傷', '悲傷'), ('恐懼', '恐懼'), ('驚訝', '驚訝'), ('厭惡', '厭惡')], default='快樂', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
