# Generated by Django 5.2.1 on 2025-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_album_name_album_title_album_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='color_mix',
            field=models.ImageField(upload_to='MoodEntry/'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='weather_icon',
            field=models.ImageField(upload_to='MoodEntry/'),
        ),
    ]
