# Generated by Django 5.2.1 on 2025-06-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_moodentry_color_mix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='mood_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='weather_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='api.moodimage'),
        ),
    ]
