# Generated by Django 5.2.1 on 2025-07-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_photo_emotion_alter_photo_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='emotion',
            field=models.CharField(choices=[('快樂', '快樂'), ('憤怒', '憤怒'), ('悲傷', '悲傷'), ('恐懼', '恐懼'), ('驚訝', '驚訝'), ('厭惡', '厭惡')], default='快樂', max_length=10),
        ),
        migrations.CreateModel(
            name='UserAchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('unlocked', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
