# Generated by Django 5.2.1 on 2025-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diary_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='ach_content',
            new_name='achContent',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='ach_title',
            new_name='achTitle',
        ),
    ]
