# Generated by Django 5.2.1 on 2025-07-27 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_ach_content_achievement_achcontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='Tot_Exp',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='Tot_Hours',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='password',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodlog',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('none', '不願透露')], default='calm', max_length=10),
        ),
    ]
