# Generated by Django 5.2.1 on 2025-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_moodlog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('none', '不願透露')], default='none', max_length=10),
        ),
    ]
