# Generated by Django 5.2.1 on 2025-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_moodlog_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='ai_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='topics',
            field=models.TextField(blank=True),
        ),
    ]
