# Generated by Django 5.2.1 on 2025-07-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_moodlog_options_remove_moodlog_tot_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
