services:
  - type: web
    name: focusbridge-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
