# Generated by Django 5.2.1 on 2025-07-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_title',
        ),
    ]
