# Generated by Django 5.2.1 on 2025-08-13 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_diary_options_diary_date_diary_mood_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'date'], name='api_todo_user_id_d350ad_idx'),
        ),
    ]
