"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# -------------------------------------------------------------------
# 1. 定義專案根目錄，並載入 .env 檔
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')  # 讀取 .env 中的環境變數

# -------------------------------------------------------------------
# 2. 安全性設定
# -------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^+l_kk9ni0h_dokk^4)ufnf_sw2ggkwz%d((xowt*y$mxxmezs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 若你要在遠端伺服器測試，可暫時設為 ['*']；正式上線時請改為具體網域
ALLOWED_HOSTS =  ['*']

# -------------------------------------------------------------------
# 3. 應用程式定義 (Installed Apps)
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Django 內建模組
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方套件
    'rest_framework',       # Django REST framework
    'rest_framework.authtoken',
    'corsheaders',          # 處理跨域請求 (CORS)

    # 自建 App
    'api',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------------
# 4. 中介層設定 (Middleware)
# -------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS Middleware 要放在 CommonMiddleware 前面
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 開啟所有來源允許跨域 (開發階段可用，正式環境請收斂)
CORS_ALLOW_ALL_ORIGINS = True

# -------------------------------------------------------------------
# 5. URL、Template 及 WSGI 設定
# -------------------------------------------------------------------
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # 若有自訂 Template 資料夾，可在此加入絕對路徑
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# -------------------------------------------------------------------
# 6. 資料庫設定 (Database)
# -------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# -------------------------------------------------------------------
# 7. 密碼驗證器 (Password Validation)
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -------------------------------------------------------------------
# 8. 國際化 (Internationalization)
# -------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Taipei'  # 設定為台北時區
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -------------------------------------------------------------------
# 9. 靜態檔案 (Static files) 及媒體檔案 (Media files)
# -------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'         # collectstatic 之後會放到這裡

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'                 # 上傳的圖片、檔案會儲存在此

# -------------------------------------------------------------------
# 10. 預設主鍵欄位類型
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# 11. Django REST framework 相關設定（可視需求自行擴充）
# -------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# -------------------------------------------------------------------
# 12. 其他自訂設定（例如：檔案大小、上傳限制等）
# -------------------------------------------------------------------
# MEDIA 上傳大小限制範例：5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880

# 如需額外設定，可在此區域新增
